# Generated by Django 5.0.4 on 2024-04-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(default='', max_length=100)),
                ('produto_valor', models.FloatField(default='')),
                ('produto_quantidade', models.IntegerField(default=0)),
            ],
        ),
    ]
